# Generated by Django 3.1.7 on 2021-07-04 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('date_of_birth', models.DateField()),
                ('birth_city', models.CharField(max_length=150)),
                ('birth_country', models.CharField(max_length=100)),
                ('height', models.IntegerField()),
                ('biography', models.TextField()),
                ('gender', models.CharField(max_length=15)),
                ('ethnicity', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('MPAA_rating', models.CharField(max_length=15)),
                ('budget', models.BigIntegerField()),
                ('gross', models.BigIntegerField()),
                ('release_date', models.DateField()),
                ('genre', models.CharField(max_length=30)),
                ('runtime', models.IntegerField()),
                ('rating', models.DecimalField(decimal_places=2, max_digits=2)),
                ('rating_count', models.IntegerField()),
                ('summary', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_name', models.CharField(max_length=150)),
                ('credit_order', models.IntegerField()),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MovieDatabase.actor')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MovieDatabase.movie')),
            ],
        ),
    ]
