# Generated by Django 3.1.7 on 2021-07-04 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MovieDatabase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='MovieDatabase.actor'),
        ),
        migrations.AlterField(
            model_name='character',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='MovieDatabase.movie'),
        ),
    ]
