# Generated by Django 3.1.7 on 2021-07-04 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieDatabase', '0004_auto_20210704_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
