# Generated by Django 3.1.7 on 2021-07-04 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieDatabase', '0007_auto_20210704_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='biography',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='actor',
            name='birth_city',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='actor',
            name='birth_country',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='actor',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='actor',
            name='ethnicity',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='actor',
            name='gender',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='actor',
            name='height',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='character_name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='credit_order',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='MPAA_rating',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='budget',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='gross',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='rating_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='runtime',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='summary',
            field=models.TextField(null=True),
        ),
    ]
